### ISSUE TITLE
Could not find `bin/android.dart` in package `will_it_run`.

### ISSUE THREAD

**Issue by fourthperson** [A7mdlbanna/will_it_run#1]
I am getting this error when I run `dart run will_it_run:android`.

I have added `will_it_run: ^1.0.3` to my dev_dependencies block

What could be the issue? Here is the output of my flutter doctor:

![image](https://github.com/A7mdlbanna/will_it_run/assets/47518399/43ea9ef4-1818-4fe4-9b54-cf7147692817)

**Comment by A7mdlbanna** [comment]
check V1.0.4

**Comment by fourthperson** [comment]
I appreciate your efforts and can see some changes for v1.0.4 in the latest commit, but `^1.0.4` is not available on pub yet.
Did you publish to pub? Or should we wait for a bit?

**Comment by A7mdlbanna** [comment]
it's available now :)
